###########################################################################################################
# DO Community Playbooks
# Playbook: Initial Server Setup
# Guide: https://www.digitalocean.com/community/tutorials/automating-initial-server-setup-with-ansible
###########################################################################################################

---
- hosts: centos2 
  become: yes 
  gather_facts: false
  vars:
    create_user: worker 
    copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    sys_packages: [ 'epel-release', 'curl', 'git', 'vim', 'nano', 'net-tools'] 

  tasks:
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Create a new regular user with sudo privileges
      user:
        name: "{{ create_user }}"
        groups: wheel
        shell: /bin/bash

    - name: Set authorized key for remote user
      authorized_key:
        user: "{{ create_user }}"
        state: present
        key: "{{ copy_local_key }}"

    - name: Disable password authentication for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'

    - name: Install required system packages
      yum: name={{ sys_packages }} state=latest

    - name: Update yum
      yum: name="*" state=latest


    - name: firewall_disable_everything
      firewalld:
            service: "*"
            state: disabled

    - name: firewalld_enable_ssh
      firewalld:
            service: ssh
            permanent: yes
            state: enabled

    - name: remove root keys
      command: rm -rf /root/.ssh && systemctl restart sshd
