---
- name: Install Epel and Remi/Update after that
  hosts: centos2  
  gather_facts: true
  become: yes
  tasks:


  - name: Install EPEL repo.
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: present

  - name: Import EPEL GPG key.
    rpm_key:
      key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
      state: present

  - name: Install remi repo.
    yum:
      name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
      state: present

  - name: Import remi GPG key.
    rpm_key:
      key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
      state: present

  - name: Update System
    yum:
      name: "*"
      state: latest
