---
# tasks file for software
- name: Install EPEL repo.
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Import EPEL GPG key.
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
    state: present

- name: Install remi repo.
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present

- name: Import remi GPG key.
  rpm_key:
    key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
    state: present
          
- name: Install required system packages
  yum: name={{ sys_packages }} state=latest

- name: Update yum
  yum: name="*" state=latest
  
- name: Ensure the ~/src-hub directory is present
  file: path=/home/{{ username }}/src-hub
                state=directory
  
- name: Clone oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git
           dest=/home/{{ username }}/src-hub/oh-my-zsh
           update=no

- name: Clone dircolors-solarized plugin
  git: repo=https://github.com/joel-porquet/zsh-dircolors-solarized
           dest=/home/{{ username }}/src-hub/oh-my-zsh/plugins/zsh-dircolors-solarized
           
- name: Clone zsh-autosuggestions plugin
  git: repo=https://github.com/zsh-users/zsh-autosuggestions.git
           dest=/home/{{ username }}/src-hub/oh-my-zsh/plugins/zsh-autosuggestions
           
- name: Create symlink to oh-my-zsh
  file: path=/home/{{ username }}/.oh-my-zsh
                src=/home/{{ username }}/src-hub/oh-my-zsh
                state=link

- name: Check if .zshrc exists
  stat: path=/home/{{ username }}/.zshrc
  register: zshrc

- name: Copy zsh config to remote
  copy: src=zshrc
                dest=/home/{{ username }}/.zshrc
                force=yes
- name: Copy Custom Agnoster Theme
  copy:
    src: agnoster.zsh-theme
    dest: /home/{{ username }}/src-hub/oh-my-zsh/themes/
        
- name: Make zsh default bin
  command: chsh -s /bin/zsh {{ username }}
